version: "2.4"

services:
  gist:
    build:
      context: .
      target: dev
      dockerfile: ./py.Dockerfile
    volumes:
      - ./src/.:/bin/app
    env_file:
      - ./.env/app.env
    stdin_open: true
    tty: true
